controller_joint_names: ['', 'shoulder_yaw_joint', 'shoulder_pitch_joint', 'elbow_pitch_joint', 'wrist_pitch_joint', 'wrist_roll_joint', 'wrist_yaw_joint', 'gripper_right_joint', 'gripper_left_joint', ]
